# Generated by Django 5.0.1 on 2026-09-15 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slide_id",
                    models.CharField(
                        help_text="مثلاً: m300، m600 - این شناسه باید با ID محصول مطابقت داشته باشد",
                        max_length=50,
                        unique=True,
                        verbose_name="شناسه اسلاید",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(max_length=200, verbose_name="عنوان فارسی"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="عنوان انگلیسی"),
                ),
                ("subtitle_fa", models.TextField(verbose_name="زیرعنوان فارسی")),
                ("subtitle_en", models.TextField(verbose_name="زیرعنوان انگلیسی")),
                (
                    "badge_fa",
                    models.CharField(
                        help_text='متن کوچک بالای عنوان - مثل "محصول جدید" یا "پیشرفته\u200cترین نسخه"',
                        max_length=100,
                        verbose_name="برچسب فارسی",
                    ),
                ),
                (
                    "badge_en",
                    models.CharField(max_length=100, verbose_name="برچسب انگلیسی"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="تصویر اصلی که در سمت راست Hero نمایش داده می\u200cشود (1200x800px توصیه می\u200cشود)",
                        upload_to="sliders/",
                        verbose_name="تصویر اصلی اسلاید",
                    ),
                ),
                (
                    "device_image",
                    models.ImageField(
                        blank=True,
                        help_text="تصویر پشتیبان در صورت خطا در بارگذاری تصویر اصلی",
                        null=True,
                        upload_to="sliders/devices/",
                        verbose_name="تصویر دستگاه",
                    ),
                ),
                (
                    "primary_cta_fa",
                    models.CharField(
                        default="مشاهده جزئیات",
                        max_length=50,
                        verbose_name="متن دکمه اصلی (فارسی)",
                    ),
                ),
                (
                    "primary_cta_en",
                    models.CharField(
                        default="View Details",
                        max_length=50,
                        verbose_name="متن دکمه اصلی (انگلیسی)",
                    ),
                ),
                (
                    "secondary_cta_fa",
                    models.CharField(
                        default="تماس با ما",
                        max_length=50,
                        verbose_name="متن دکمه ثانویه (فارسی)",
                    ),
                ),
                (
                    "secondary_cta_en",
                    models.CharField(
                        default="Contact Us",
                        max_length=50,
                        verbose_name="متن دکمه ثانویه (انگلیسی)",
                    ),
                ),
                (
                    "custom_link",
                    models.URLField(
                        blank=True,
                        help_text="اگر خالی بگذارید، به صفحه محصول لینک می\u200cشود",
                        null=True,
                        verbose_name="لینک سفارشی",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="آیا این اسلاید نمایش داده شود؟",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="اسلایدها بر اساس این عدد مرتب می\u200cشوند (کوچکترین عدد اولویت دارد)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "اسلاید صفحه اصلی",
                "verbose_name_plural": "اسلایدرهای صفحه اصلی",
                "ordering": ["order", "slide_id"],
            },
        ),
        migrations.CreateModel(
            name="SliderHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_fa",
                    models.CharField(
                        help_text='مثلاً: "پردازنده" یا "باتری"',
                        max_length=100,
                        verbose_name="برچسب فارسی",
                    ),
                ),
                (
                    "label_en",
                    models.CharField(max_length=100, verbose_name="برچسب انگلیسی"),
                ),
                (
                    "value_fa",
                    models.CharField(
                        help_text='مثلاً: "Quad-Core A7" یا "5000 mAh"',
                        max_length=200,
                        verbose_name="مقدار فارسی",
                    ),
                ),
                (
                    "value_en",
                    models.CharField(max_length=200, verbose_name="مقدار انگلیسی"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="حداکثر 4 نکته برجسته نمایش داده می\u200cشود (0 تا 3)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="ترتیب",
                    ),
                ),
                (
                    "slider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="homepage.homeslider",
                        verbose_name="اسلاید",
                    ),
                ),
            ],
            options={
                "verbose_name": "نکته برجسته اسلاید",
                "verbose_name_plural": "نکات برجسته اسلایدها",
                "ordering": ["order"],
            },
        ),
    ]
