# Generated by Django 5.0.1 on 2026-09-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeslider",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="تصویر اصلی که در سمت راست Hero نمایش داده می\u200cشود (1200x800px توصیه می\u200cشود)",
                null=True,
                upload_to="sliders/",
                verbose_name="تصویر اصلی اسلاید",
            ),
        ),
    ]
