# Generated by Django 6.1.1 on 2026-09-14 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(help_text='شناسه یکتا (مثل m300, m600)', max_length=50, primary_key=True, serialize=False)),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=200, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary_fa', models.TextField(verbose_name='خلاصه توضیحات فارسی')),
                ('summary_en', models.TextField(verbose_name='خلاصه توضیحات انگلیسی')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر اصلی محصول')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='products/banners/', verbose_name='تصویر بنر')),
                ('device_image', models.ImageField(blank=True, null=True, upload_to='products/devices/', verbose_name='تصویر دستگاه')),
                ('os_type', models.CharField(choices=[('RTOS', 'RTOS'), ('Linux', 'Linux'), ('Android', 'Android'), ('RTOS/Linux', 'RTOS/Linux'), ('Linux/Android', 'Linux/Android')], max_length=50, verbose_name='سیستم عامل')),
                ('tag', models.CharField(help_text='مثل RTOS / Linux', max_length=100, verbose_name='برچسب محصول')),
                ('display', models.CharField(max_length=200, verbose_name='صفحه نمایش')),
                ('processor', models.CharField(max_length=200, verbose_name='پردازنده')),
                ('memory', models.CharField(max_length=200, verbose_name='حافظه')),
                ('battery', models.CharField(max_length=200, verbose_name='باتری')),
                ('connectivity', models.CharField(max_length=300, verbose_name='قابلیت\u200cهای ارتباطی')),
                ('sim_sam', models.CharField(max_length=200, verbose_name='اسلات SIM و SAM')),
                ('dimensions', models.CharField(max_length=200, verbose_name='ابعاد و وزن')),
                ('printer', models.CharField(max_length=300, verbose_name='پرینتر')),
                ('card_readers', models.CharField(max_length=300, verbose_name='کارتخوان\u200cها')),
                ('certifications', models.CharField(max_length=300, verbose_name='گواهینامه\u200cها')),
                ('keyboard', models.CharField(blank=True, max_length=200, null=True, verbose_name='کیبورد')),
                ('catalog_file', models.FileField(blank=True, null=True, upload_to='catalogs/', verbose_name='فایل کاتالوگ PDF')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('coming_soon', 'به زودی')], default='active', max_length=20, verbose_name='وضعیت')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_fa', models.TextField(verbose_name='ویژگی فارسی')),
                ('feature_en', models.TextField(verbose_name='ویژگی انگلیسی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='products.product')),
            ],
            options={
                'verbose_name': 'نکته برجسته',
                'verbose_name_plural': 'نکات برجسته',
                'ordering': ['order'],
            },
        ),
    ]
